/* groovylint-disable CompileStatic, GStringExpressionWithinString */
pipeline {
    agent any

    tools {
        maven 'MAVEN3.9'
        jdk 'JDK17'
    }

    environment {
        cluster = 'vprofile-app-prod'
        service = 'vprofile-app-task-service-prod'
    }

    stages {
        stage('Deploy to Staging ECS') {
            steps {
                withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }

    post {
        always {
            echo 'Slack Notifications.'
            // slackSend channel: '#jenkinscicd',
            //     color: COLOR_MAP[currentBuild.currentResult],
            //     /* groovylint-disable-next-line LineLength */
            //     message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at : ${env.BUILD_URL}"
        }
    }
}
